version: '3.8'

services:
  fastapi:
    image: fastapi:latest
    container_name: fastapi_bootstrap
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:80"
    environment:
      - ENVIRONMENT=development
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_HOST=${DB_HOST}
      - DB_NAME=${DB_NAME}
    volumes:
      - ./mount:/src
      - ./mount/scripts:/src/scripts
      - ./mount/alembic:/src/alembic
    depends_on:
      - pgdb
      - redis

  pgdb:
    image: postgres:13
    container_name: fast_pgdb
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - ./postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:latest
    container_name: fast_redis
    ports:
      - "6379:6379"
    volumes:
      - ./redis_data:/data

volumes:
  postgres_data:
  redis_data:
