"""users table init

Revision ID: 66861a624fd3
Revises:
Create Date: 2025-01-05 05:38:41.312630

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '66861a624fd3'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
	# ### commands auto generated by Alembic - please adjust! ###
	op.create_table(
		'users',
		sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
		sa.Column('username', sa.String(length=50), nullable=False),
		sa.Column('email', sa.String(length=255), nullable=False),
		sa.Column('full_name', sa.String(length=100), nullable=True),
		sa.Column('hashed_password', sa.String(length=255), nullable=False),
		sa.Column('is_active', sa.Boolean(), nullable=False),
		sa.Column(
			'created_at',
			sa.DateTime(timezone=True),
			server_default=sa.text('now()'),
			nullable=True,
		),
		sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
		sa.PrimaryKeyConstraint('id'),
		sa.UniqueConstraint('email'),
		sa.UniqueConstraint('username'),
	)
	# ### end Alembic commands ###


def downgrade() -> None:
	# ### commands auto generated by Alembic - please adjust! ###
	op.drop_table('users')
	# ### end Alembic commands ###
