"""remove permissions

Revision ID: 9ba76cc68e40
Revises: c542442d1595
Create Date: 2025-07-27 00:10:47.337428

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9ba76cc68e40'
down_revision: Union[str, None] = 'c542442d1595'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
	# ### commands auto generated by Alembic - please adjust! ###
	op.drop_column('roles', 'permissions')
	# ### end Alembic commands ###


def downgrade() -> None:
	# ### commands auto generated by Alembic - please adjust! ###
	op.add_column(
		'roles',
		sa.Column(
			'permissions',
			postgresql.JSON(astext_type=sa.Text()),
			autoincrement=False,
			nullable=True,
		),
	)
	# ### end Alembic commands ###
